### ISSUE TITLE
Media not imported

### ISSUE THREAD

**Issue by asecondwill** [camfindlay/silverstripe-wordpressimport#24]
On running the importer the posts are brought into Silverstripe, but not the featured images or images added to the wysiwyg content.

I'm on SS 3.2, blog 2 (downgraded for import)

**Comment by camfindlay** [comment]
The current version of the module doesn't move the media you'll need to manually move the folder from your WP site into the assets folder. If you keep that folder structure from 'wp-content' folder /YEAR/MONTH/file.jpg when the import of text data occurs it converts references to the images. See https://github.com/camfindlay/silverstripe-wordpressimport/blob/master/README.md#usage-overview. I'll close this however we'll raise a separate issue as a feature request for image imports during the migration process.

**Comment by asecondwill** [comment]
thats great, thanks cam
